/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.2.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module halfAdder
    ( // Inputs
      input  i_A
    , input  i_B

      // Outputs
    , output wire  o_SUM
    , output wire  o_COUT
    );
  wire  c$app_arg;
  wire  c$app_arg_0;
  wire  c$case_alt;
  wire [1:0] o;

  assign c$app_arg = i_A ? i_B : 1'b0;

  assign c$app_arg_0 = i_A ? c$case_alt : i_B;

  assign c$case_alt = i_B ? 1'b0 : 1'b1;

  assign o = {c$app_arg_0,c$app_arg};

  assign o_SUM = o[1:1];

  assign o_COUT = o[0:0];


endmodule

