//
// Generated by Bluespec Compiler (build 0000000)
//
// On Wed Nov 18 22:20:04 PST 2020
//
//
// Ports:
// Name                         I/O  size props
// o_S                            O     1
// o_Cout                         O     1
// CLK                            I     1 unused
// RST_N                          I     1 unused
// i_A                            I     1
// i_B                            I     1
//
// Combinational paths from inputs to outputs:
//   (i_A, i_B) -> o_S
//   (i_A, i_B) -> o_Cout
//
//
// A half adder written in Bluespec SystemVerilog
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module halfadder(
		 

		 i_A,
		 i_B,

		 o_S,

		 o_Cout);
  
  

  // action method drive
  input  i_A;
  input  i_B;

  // value method sum
  output o_S;

  // value method carry
  output o_Cout;

  // signals for module outputs
  wire o_Cout, o_S;

  // value method sum
  assign o_S = i_A ^ i_B ;

  // value method carry
  assign o_Cout = i_A & i_B ;
endmodule  // halfadder

