import sys
def main():
    fo = open("popcount8.v","w")
    fo.write("module popcount8 (\n")
    fo.write("\tinput wire i_CLK,\n")
    fo.write("\tinput wire i_INVERSE,\n")
    fo.write("\tinput wire [7:0] i_INPUT,\n")
    fo.write("\toutput reg [3:0] o_OUTPUT\n")
    fo.write(");\n")
    fo.write("\n")
    fo.write("reg [3:0] r_POPCOUNT;\n")
    fo.write("reg [3:0] r_INVERSE_POPCOUNT;\n")
    fo.write("\n")
    fo.write("always@(posedge i_CLK)\n")
    fo.write("begin\n")
    fo.write("\tcase(i_INPUT)\n")
    end = pow(2,8)
    for i in range(0,end):
        fo.write("\t\t8'd%d:\n" % i)
        fo.write("\t\tbegin\n")
        fo.write("\t\t\tr_POPCOUNT <= 4'd%d;\n" % bin(i).count("1"))
        fo.write("\t\t\tr_INVERSE_POPCOUNT <= 4'd%d;\n" % (8 - bin(i).count("1"))) #Get the complement
        fo.write("\t\tend\n")
    fo.write("\tendcase\n")
    fo.write("end\n")
    fo.write("always@(posedge i_CLK)\n")
    fo.write("begin\n")
    fo.write("\tif(i_INVERSE == 1'b1)\n")
    fo.write("\t\to_OUTPUT <= r_INVERSE_POPCOUNT;\n")
    fo.write("\telse\n")
    fo.write("\t\to_OUTPUT <= r_POPCOUNT;\n")
    fo.write("end\n")
    fo.write("endmodule")
main()
